/**
 * Auto-generated icon registry and exports
 * This file is generated by scripts/build-icons.ts
 * Do not edit manually
 */

import type { IconRegistry } from '../core/types';

import { Sparkle } from './system/Sparkle';

// Export all icons for named imports
export {
  Sparkle
};

// Registry for dynamic icon loading
export const registry: IconRegistry = {
  Sparkle,
};
