/**
 * Auto-generated icon registry and exports
 * This file is generated by scripts/build-icons.ts
 * Do not edit manually
 */

import type { IconRegistry } from '../core/types';

import { GithubDark } from './brand/GithubDark';
import { GithubLight } from './brand/GithubLight';
import { Google } from './brand/Google';
import { PasskeyDark } from './brand/PasskeyDark';
import { PasskeyLight } from './brand/PasskeyLight';
import { AtSign } from './system/AtSign';
import { Chat } from './system/Chat';
import { Folder } from './system/Folder';
import { Home } from './system/Home';
import { Inbox } from './system/Inbox';
import { Layers } from './system/Layers';
import { Password } from './system/Password';
import { Settings } from './system/Settings';
import { Sparkle } from './system/Sparkle';
import { SquareGrid } from './system/SquareGrid';
import { User } from './system/User';
import { Users } from './system/Users';

// Export all icons for named imports
export {
  GithubDark,
  GithubLight,
  Google,
  PasskeyDark,
  PasskeyLight,
  AtSign,
  Chat,
  Folder,
  Home,
  Inbox,
  Layers,
  Password,
  Settings,
  Sparkle,
  SquareGrid,
  User,
  Users
};

// Registry for dynamic icon loading
export const registry: IconRegistry = {
  GithubDark,
  GithubLight,
  Google,
  PasskeyDark,
  PasskeyLight,
  AtSign,
  Chat,
  Folder,
  Home,
  Inbox,
  Layers,
  Password,
  Settings,
  Sparkle,
  SquareGrid,
  User,
  Users,
};
