/**
 * Auto-generated icon registry and exports
 * This file is generated by scripts/build-icons.ts
 * Do not edit manually
 */

import type { IconRegistry } from '../core/types';

import { GithubDark } from './brand/GithubDark';
import { GithubLight } from './brand/GithubLight';
import { Google } from './brand/Google';
import { PasskeyDark } from './brand/PasskeyDark';
import { PasskeyLight } from './brand/PasskeyLight';
import { AtSignDark } from './system/AtSignDark';
import { AtSignLight } from './system/AtSignLight';
import { Chat } from './system/Chat';
import { Folder } from './system/Folder';
import { Home } from './system/Home';
import { Inbox } from './system/Inbox';
import { Layers } from './system/Layers';
import { Lock } from './system/Lock';
import { PasswordDark } from './system/PasswordDark';
import { PasswordLight } from './system/PasswordLight';
import { PowerOff } from './system/PowerOff';
import { Settings } from './system/Settings';
import { Sitemap } from './system/Sitemap';
import { Sparkle } from './system/Sparkle';
import { SquareGrid } from './system/SquareGrid';
import { User } from './system/User';
import { Users } from './system/Users';

// Export all icons for named imports
export {
  GithubDark,
  GithubLight,
  Google,
  PasskeyDark,
  PasskeyLight,
  AtSignDark,
  AtSignLight,
  Chat,
  Folder,
  Home,
  Inbox,
  Layers,
  Lock,
  PasswordDark,
  PasswordLight,
  PowerOff,
  Settings,
  Sitemap,
  Sparkle,
  SquareGrid,
  User,
  Users
};

// Registry for dynamic icon loading
export const registry: IconRegistry = {
  GithubDark,
  GithubLight,
  Google,
  PasskeyDark,
  PasskeyLight,
  AtSignDark,
  AtSignLight,
  Chat,
  Folder,
  Home,
  Inbox,
  Layers,
  Lock,
  PasswordDark,
  PasswordLight,
  PowerOff,
  Settings,
  Sitemap,
  Sparkle,
  SquareGrid,
  User,
  Users,
};
